version: '3'

services:
  nginx:
    image: ghcr.io/getimages/nginx:1.23.3-alpine
    container_name: test_nginx
    volumes:
      - ./:/app/
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs/:/var/log/nginx/
    ports:
      - "8080:80"
    working_dir: /app
    restart: always
    depends_on:
      - php
    networks:
      - test

  php:
    build: ./.docker/php
    image: api_php
    container_name: test_php
    restart: always
    working_dir: /app
    ports:
      - ${PHP_EXPOSED_PORT:-0}:80
    volumes:
      - ./:/app/
    depends_on:
      - mysql
      - redis
    networks:
      - test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: test_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "8081:80"
    networks:
      - test

  mysql:
    image: ghcr.io/getimages/mysql:8.0.31-debian
    container_name: test_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - test

  redis:
    image: ghcr.io/getimages/redis:7.0.7-bullseye
    container_name: test_redis
    restart: always
    ports:
      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
    networks:
      - test

networks:
  test:
